### ISSUE TITLE
parseToggles return error

### ISSUE THREAD

**Issue by bayuleo** [Unleash/unleash_proxy_client_flutter#15]
### Describe the bug

Hi team, i found error from your Flutter SDK code. I think it because ToggleConfig cant handle null value.

### Logs, error output, etc.

```bash
type 'Null' is not a subtype of type 'bool'
```

### Screenshots

![Screen Shot 2023-05-23 at 11 50 57](https://github.com/Unleash/unleash_proxy_client_flutter/assets/23091351/ba27522a-fcf3-4f43-83c5-443d4fee484f)

### Unleash version

1.2.0

### Subscription type

None

### Hosting type

None

**Comment by kwasniew** [comment]
@bayuleo thanks for raising this issue. 
This PR: https://github.com/Unleash/unleash_proxy_client_flutter/pull/16 should fix it.
Please check version 1.2.1 and let us know if everything works for you.

**Comment by bayuleo** [comment]
@kwasniew everything work well on 1.2.1, thanks
