### ISSUE TITLE
Add multiple context fields at the same time

### ISSUE THREAD

**Issue by emersonsiega** [Unleash/unleash_proxy_client_flutter#29]
### Describe the feature request

We need to add multiple context fields at the same time and fetch the feature toggles just once.

### Background

Currently it's possible to add context fields in two different ways:
- Update the entire context field data
- Add context fields one by one

The first option will override existent data, and this is not the behavior we want.
The second option will fire a request to update the toggles. If we have 10 context fields, it'll fire 10 requests.

**Comment by kwasniew** [comment]
Thanks for raising this issue. The reason why we haven't added update multiple context fields is because we try to keep the API surface area small and consistent across all language SDKs. Our recommendation is to keep a reference to the context and overwrite fields you like to update and pass the whole context again. Is it doable in your app? 

Also, I'm wondering if a convenience method on the UnleashContext would help.

**Comment by emersonsiega** [comment]
> Thanks for raising this issue. The reason why we haven't added update multiple context fields is because we try to keep the API surface area small and consistent across all language SDKs. Our recommendation is to keep a reference to the context and overwrite fields you like to update and pass the whole context again. Is it doable in your app?
> 
> Also, I'm wondering if a convenience method on the UnleashContext would help.

Hi @kwasniew

I think we can do this by hand, as you suggest... it would add more work on our side and can lead developers to mess up with the sessionId and other data, but it probably works... 

However, I believe this situation is a very common use case.

For instance, our app adds a considerably large list of context fields after the user logged in. After that, some standalone modules (this app has more than 30 standalone modules) can add more fields to the context, in addition to the existent ones. We can't use the current methods exposed by the SDK, cause they run a query after every new context field added. 

It seems a common use case for me, and other people can benefit of it... 

Can't you consider add this method in other language SDKs, keeping them consistent?

**Comment by kwasniew** [comment]
Thanks for providing your context. I'm willing to give this new API method a benefit of a doubt and try it out. You can test it with the latest 1.5.0 release (https://pub.dev/packages/unleash_proxy_client_flutter/versions/1.5.0)

**Comment by kwasniew** [comment]
@emersonsiega Once you tested the new capability please let me know if I can close this issue and https://github.com/Unleash/unleash_proxy_client_flutter/pull/30
