### ISSUE TITLE
_TypeError. type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by 1mavic** [Unleash/unleash_proxy_client_flutter#39]
### Describe the bug

Hi!
Getting error from some users devices in sentry.

_TypeError
type 'String' is not a subtype of type 'int' of 'index'

### Steps to reproduce the bug

Looks like in line

`final data = jsonDecode(body)['toggles'];`
After decode Dart thinks, that type is List and no map.

### Logs, error output, etc.

```bash
StackTrase:
_TypeError: type 'String' is not a subtype of type 'int' of 'index'
  File "parse_stringify_toggles.dart", line 8, in parseToggles
  File "unleash_proxy_client_flutter.dart", line 253, in UnleashClient._fetchTogglesFromStorage
  File "<asynchronous suspension>"
  File "unleash_proxy_client_flutter.dart", line 162, in UnleashClient._init
```

### Subscription type

None

### Hosting type

Self-hosted

### SDK information (language and version)

flutter sdk 1.4.0

**Comment by daveleek** [comment]
Hello @1mavic and thank you for raising this! We'll have a look and get back to you!

**Comment by andreas-unleash** [comment]
Hi @1mavic , can you share how you configure your client?  Do you use a custom storage provider?

**Comment by 1mavic** [comment]
@andreas-unleash Hi!
no, no custom storage implemented.

unleashClient = UnleashClient(
      url: Uri.parse(_unleashClientUrl),
      clientKey: _clientKey,
      appName: 'default',
      fetcher: _fetcher,
      poster: _poster,
      environment: _env == 'prod' ? 'production' : 'development',
      refreshInterval: int.tryParse(_refreshInterval) ?? 3600,
    );

**Comment by andreas-unleash** [comment]
Thanks @1mavic .  That looks ok.  Any change you can provide a minimal repo reproducing the issue?

**Comment by 1mavic** [comment]
We get this exception only in sentry, for only 3 users with Android devices.

we init UnleashClient with settings from above. Thats all)
on init it calls _fetchTogglesFromStorage and then parseToggles method from parse_stringify_toggles.dart

**Comment by andreas-unleash** [comment]
Thanks for bringing this to our attention.  [This PR](https://github.com/Unleash/unleash_proxy_client_flutter/pull/40) should take care of the exception
