### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by chrisjung01** [Unleash/unleash_proxy_client_flutter#45]
### Describe the bug

Thank you guys for your great work. 

I would request a dependency update from the `uuid` and `shared_preferences` pubs to the new versions. 
Because I was not able to use the last version of the `unleash_proxy_client_flutter`, I'm stuck at version 0.0.1. 

The last version of the `shared_preferences` pub is `2.2.3` [link](https://pub.dev/packages/shared_preferences)
And the last version of the `uuid` pub is `4.4.0` [link](https://pub.dev/packages/uuid)

### Steps to reproduce the bug

1. Create a new flutter project
2. Add `unleash_proxy_client_flutter` with `flutter pub add unleash_proxy_client_flutter`
3. Add `uuid` with `flutter pub add uuid`
4. Replace the uuid version in the `pubspec.yaml` with the current version `uuid: ^4.4.0`
5. Get the dependencies with `flutter pub get`

### Expected behavior

I expected that there was no conflict with the current version of the `uuid` package. 

### Logs, error output, etc.

```bash
Because unleash_proxy_client_flutter >=1.5.0 depends on uuid >=3.0.7 <4.3.0 and my_new_app depends on uuid ^4.3.3, unleash_proxy_client_flutter >=1.5.0 is forbidden.
So, because my_new_app depends on unleash_proxy_client_flutter ^1.5.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on unleash_proxy_client_flutter: flutter pub add unleash_proxy_client_flutter:^0.0.1



pubspec.lock:
  unleash_proxy_client_flutter:
    dependency: "direct main"
    description:
      name: unleash_proxy_client_flutter
      sha256: "29a325d45bf56a39bbc076598134854e8b8ca7cc23d68bfae21a43f672e5b2a8"
      url: "https://pub.dev"
    source: hosted
    version: "0.0.1"
```

### Unleash version

0.0.1

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

**Comment by chrisjung01** [comment]
I try to upgrade this dependencies, but this repository is locked for me and I'm not able to create any branch 😄

**Comment by kwasniew** [comment]
@chrisjung01 thanks for reporting this issue. Can you please confirm if version 1.5.2 fixes your issue? We extended supported version ranges for uuid and shared_preferences.
