### ISSUE TITLE
A way to get all feature flags for current project

### ISSUE THREAD

**Issue by joachimbulow** [Unleash/unleash_proxy_client_flutter#52]
### Describe the feature request

I think a pretty common use case (maybe?) would be fetching all flags to apply properties in external analytics platform.

This would be very easy with a way to fetch all flags. 

Can we get this asap?

Might look into a solution myself as well

### Background

We use Mixpanel and want to propagate backend flags into events using `super properties` without updating our client for every new flag.

### Solution suggestions

Simple event like what it seems you can in `react`
https://stackoverflow.com/questions/76649494/is-there-a-way-to-get-all-flags-from-unleash-in-react

**Comment by joachimbulow** [comment]
Exists on the client `toggles`

**Comment by joachimbulow** [comment]
Actually, reopened due to an issue i am not sure if i can easily circumvent:

Toggles on the client only contain the flags which are actually `active`.

I need a surefire way to get all flags for a project. Any hints?

**Comment by ivarconr** [comment]
> I need a surefire way to get all flags for a project. Any hints?

If you use [Unleash Edge](https://github.com/Unleash/unleash-edge) you can use the "/api/frontend/all" endpoint to get all flags. Keep in mind this will increase the payload sent to all clients.

**Comment by joachimbulow** [comment]
Legend, will try that in a minute

**Comment by joachimbulow** [comment]
Alright hit that endpoint manually. 
Was able to leverage the `ToggleConfig` class `fromJson` method to parse as well 🙏 
Not really sure why you decided to strip the _name_ from that one?
Its in the payload, so just had to manually do `rawJson[name]` 🤔 

Anyway thanks a lot we firing mad super properties all over the place now
