### ISSUE TITLE
Certificate verification

### ISSUE THREAD

**Issue by mikklfr** [Unleash/unleash_proxy_client_flutter#9]
### Describe the feature request

I wish to be able to add a TLS/SSL signature in SDK configuration that would be verified by the HTTP Client used in Unleash.
This feature would make traffic interception and flip "hacking" much harder.

### Background

We are currently using Unleash and we're happy with the solution.

Without pinning an attacker could easily intercept traffic on a device they own (they could add a Charles certificate for instance) and then switch values without having to decompile the application.

### Solution suggestions

Maybe a ```List<String>``` of SHA hashes or a wrapping Object could be a good start to allow both SelfHosted and CloudHosted to be setup this verification easily.

Here is how dio packages usually allow hashes to be passed to clients:
https://github.com/cfug/dio/tree/main/dio#https-certificate-verification

**Comment by mikklfr** [comment]
Manage to do something using https://pub.dev/packages/http_certificate_pinning
When setting up SDK you can override fetcher and poster like this:

```
    var unleash = UnleashClient(
        fetcher: secureFetcher,
        poster: securePoster,
       ...
     );
```

Then you can bridge that with the verification you need:

```
final secureClient = SecureHttpClient.build(["sha256/..."]);

Future<http.Response> secureFetcher(http.Request request) {
  return secureClient.get(request.url, headers: request.headers);
}

Future<http.Response> securePoster(http.Request request) {
  return secureClient.post(request.url,
      headers: request.headers, body: request.body);
}
```

**Comment by kwasniew** [comment]
Yeap, that's our recommended approach and the reason we allow for dependency injection. We don't want to be too opinionated about the HTTP client semantics. So as long as your opinionated client matches our minimum API you're good.
